Add ignore for org.freedesktop.DBus.Error.NoReply

diff --git a/test_logwarn b/test_logwarn
--- a/test_logwarn
+++ b/test_logwarn
@@ -41,4 +41,5 @@ echo $out | grep -q '\[websockets:error] Unknown property received from worker 5
 echo $out | grep -q '\[websockets:warn] dead job 997744 aborted as incomplete' && exit 2
 echo $out | grep -q '\[10709:error\] Failed to login: OpenID provider returned invalid data\. Please retry again' && exit 2
 echo $out | grep -q '\[websockets:warn\] A message received from unknown worker connection' && exit 2
+echo $out | grep -q '\[4087:error] org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.' && exit 2
 echo "PASSED"
