Add ignore for 'File exists' (poo#53474)

diff --git a/test_logwarn b/test_logwarn
--- a/test_logwarn
+++ b/test_logwarn
@@ -55,4 +55,5 @@ echo $out | grep -q '\[.*warn\] A message received from unknown worker connectio
 echo $out | grep -q '\[.*warn\] Unable to get filename' && exit 2
 echo $out | grep -q '\[.*warn\] has no child, check its machine placed' && exit 2
 echo $out | grep -q '\[error\] DBIx.*number of parameters must be between.*OpenQA/WebAPI/Controller/API/V1/Job.pm' && exit 2
+echo $out | grep -q '\[error\] mkdir /var/lib/openqa/images/0bf/862/.thumbs: File exists at /usr/share/openqa/script/../lib/OpenQA/Schema/Result/Jobs.pm line 1227' && exit 2
 echo "PASSED"
