Add ignore for 'number of parameters must be between ... (poo#53435)

diff --git a/test_logwarn b/test_logwarn
--- a/test_logwarn
+++ b/test_logwarn
@@ -54,4 +54,5 @@ echo $out | grep -q 'DBI Exception' && exit 2
 echo $out | grep -q '\[.*warn\] A message received from unknown worker connection' && exit 2
 echo $out | grep -q '\[.*warn\] Unable to get filename' && exit 2
 echo $out | grep -q '\[.*warn\] has no child, check its machine placed' && exit 2
+echo $out | grep -q '\[error\] DBIx.*number of parameters must be between.*OpenQA/WebAPI/Controller/API/V1/Job.pm' && exit 2
 echo "PASSED"
