Add ignore for 'OPENQA_HOST_URL' (poo#53399)

diff --git a/test_logwarn b/test_logwarn
--- a/test_logwarn
+++ b/test_logwarn
@@ -52,4 +52,5 @@ echo $out | grep -q '\[websockets:warn] dead job 997744 aborted as incomplete' &
 echo $out | grep -q 'error\] .*api_description' && exit 2
 echo $out | grep -q 'DBI Exception' && exit 2
 echo $out | grep -q '\[.*warn\] A message received from unknown worker connection' && exit 2
+echo $out | grep -q '\[.*warn\] Unable to get filename' && exit 2
 echo "PASSED"
