Ignore known warning poo#19730 'can not remove png'

diff --git a/test_logwarn b/test_logwarn
--- a/test_logwarn
+++ b/test_logwarn
@@ -35,4 +35,5 @@ echo $out | grep -q '\[31798:warn\] no products found, retrying version wildcard
 echo $out | grep -q '\[14008:warn\] START_AFTER_TEST=RAID0:ppc64le not found - check for typos and dependency cycles' && exit 2
 echo $out | grep -q 'Worker not found for given connection during connection close' && exit 2
 echo $out | grep -q '\[15550:warn] AMQP connection error: SSL connect attempt failed with unknown error' && exit 2
+echo $out | grep -q "can't remove d81/349/2cab90e04faac6f7a112c5ed90.png" && exit 2
 echo "PASSED"
