Ignore known and reported warnings

diff --git a/test_logwarn b/test_logwarn
--- a/test_logwarn
+++ b/test_logwarn
@@ -1,9 +1,9 @@
 #!/bin/sh -e
 set -o pipefail
-out=$(logwarn -f /dev/null -z -m '\[.*:(debug|info|warn|error)\]' in.log '\[.*:(warn|error)\]' '!\[.*:(debug|info)\]') || true
+
+out=$(env options="-f /dev/null -z" file=in.log sh -ex ./logwarn_openqa) || true
 
 echo "test error messages are included"
-echo $out | grep -q ':error.*Asset iso/foo.iso is not in any job group'
 echo $out | grep -q ':error.*File iso/bar.iso is not a registered asset'
 echo $out | grep -q ':error.*MISSING S:scheduled R:none'
 
@@ -19,5 +19,11 @@ echo $out | grep -q '\[Thu Oct  6 01:15:54 2016\] \[27316:debug\] dispatching IP
 echo $out | grep -q 'blocking   => 0,' && exit 2
 echo $out | grep -q 'cpu_modelname => undef,' && exit 2
 echo $out | grep -q '^\]$' && exit 2
+
+echo "Known and blacklisted log lines are not included"
+echo $out | grep -q '\[4608:warn\] 619442 got a status update but has no worker. huh?' && exit 2
+echo $out | grep -q '\[8980:warn\] 619391 got an artefact but has no worker. huh?' && exit 2
+echo $out | grep -q ':error.*Asset iso/foo.iso is not in any job group' && exit 2
+
 
 echo "PASSED"
